Clarify STL file dimensions
maxbbraun/pisight pull request #7
Opened 2020-10-06 12:35 UTC by htreu

When uploading the STL file to a 3D print service the dimensions for the STL file must be specified. Clarify in the readme `mm` was used.

2020-10-09 04:23 UTC, cooperpellaton commented
Bump on this. Was unsure of dimensions until I popped open [`PiSight.stl`](PiSight.stl) in Fusion and saw the units measured in `mm`. Having additional info would be good for others!
<img width="209" alt="Screen Shot 2020-10-08 at 9 22 14 PM" src="https://user-images.githubusercontent.com/5178017/95543039-57620a80-09ac-11eb-90ab-dc628e900d94.png">

2020-10-10 16:35 UTC, maxbbraun requested changes
Thank you! Suggested a small edit.

2020-10-10 16:35 UTC, maxbbraun commented on README.md
> +| 3D-printed frame | Use [`PiSight.stl`](PiSight.stl) or [`PiSight.step`](PiSight.step), cost varies significantly depending on material quality. Dimensions measured in `mm`.  | [$50 to $200](https:/
How about this for consistency:

```suggestion
| 3D-printed frame | Use [`PiSight.stl`](PiSight.stl) or [`PiSight.step`](PiSight.step), dimensions in mm, cost varies significantly depending on material quality | [$50 to $200](https://www.fictiv.com) |
```

2020-11-22 13:47 UTC, htreu commented
This is ready to go.

2020-11-22 17:34 UTC, merged